nome = str(input('Digite seu nome completo: ')).strip()
separa = nome.split()
print('Analisando seu nome... ')
print('Seu nome em maíuscula é {}'.format(nome.upper()))
print('Seu nome em minusculo é {}'.format(nome.lower()))
print('Seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], nome.find(' ')))